name: GitHub Actions Demo
on: [push]
jobs:
  test_checkout:
    runs-on: ubuntu-latest
    env:
      fruit: apple
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: welcome message
        run: | 
          echo "my first github actions job" > output.txt
          echo "my favorite fruit is ${{ env.fruit }}" >> output.txt

      - name: list files
        run: ls

      - name: Read file
        run: cat README.md

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.txt

  read_output:
    runs-on: ubuntu-latest
    needs: test_checkout
    steps:
      - name: read artifact
        run: cat output.txt  # likely to fail if "needs" not specified for this job